/**
 * Dummy material data for the visualizer when the API returns no products.
 * Images reference files in the Next.js /public folder.
 */
export const DUMMY_MATERIALS = [
    {
        _id: 'dummy-1',
        name: 'Venetian Plaster White',
        color: 'White',
        price: 2800,
        mrp: 3500,
        selling_price: 2800,
        images: ['/Images/Image.png'],
        category: 'Plaster',
        product_type: 'Plaster',
        skucode: 'VP-WHT-001',
        dynamicAttributes: [
            { key: 'Finish', value: 'Matte' },
            { key: 'Application', value: 'Interior Walls' },
            { key: 'Coverage', value: '10–12 sq.ft / kg' },
        ],
    },
    {
        _id: 'dummy-2',
        name: 'Terrazzo Blush Rose',
        color: 'Rose',
        price: 4200,
        mrp: 5000,
        selling_price: 4200,
        images: ['/Images/Image_2.png'],
        category: 'Stone',
        product_type: 'Stone',
        skucode: 'TZ-BLS-002',
        dynamicAttributes: [
            { key: 'Finish', value: 'Polished' },
            { key: 'Application', value: 'Flooring, Countertops' },
            { key: 'Thickness', value: '12 mm' },
        ],
    },
    {
        _id: 'dummy-3',
        name: 'Concrete Grey Matte',
        color: 'Grey',
        price: 1950,
        mrp: 2400,
        selling_price: 1950,
        images: ['/Images/Image_3.png'],
        category: 'Concrete',
        product_type: 'Concrete',
        skucode: 'CG-GRY-003',
        dynamicAttributes: [
            { key: 'Finish', value: 'Matte' },
            { key: 'Application', value: 'Walls & Ceilings' },
            { key: 'Coverage', value: '8–10 sq.ft / kg' },
        ],
    },
    {
        _id: 'dummy-4',
        name: 'Linen Weave Warm Sand',
        color: 'Sand',
        price: 3600,
        mrp: 4200,
        selling_price: 3600,
        images: ['/Images/Image_4.png'],
        category: 'Textile',
        product_type: 'Textile',
        skucode: 'LW-SND-004',
        dynamicAttributes: [
            { key: 'Material', value: '100% Linen' },
            { key: 'Width', value: '140 cm' },
            { key: 'Weight', value: '280 gsm' },
        ],
    },
    {
        _id: 'dummy-5',
        name: 'Teak Wood Natural',
        color: 'Brown',
        price: 6800,
        mrp: 8000,
        selling_price: 6800,
        images: ['/Images/Image_5.png'],
        category: 'Wood',
        product_type: 'Wood',
        skucode: 'TW-NAT-005',
        dynamicAttributes: [
            { key: 'Finish', value: 'Oil' },
            { key: 'Application', value: 'Flooring, Panelling' },
            { key: 'Thickness', value: '18 mm' },
        ],
    },
    {
        _id: 'dummy-6',
        name: 'Marble Calacatta Gold',
        color: 'Gold',
        price: 12000,
        mrp: 15000,
        selling_price: 12000,
        images: ['/Images/Image_6.png'],
        category: 'Stone',
        product_type: 'Stone',
        skucode: 'MC-GLD-006',
        dynamicAttributes: [
            { key: 'Finish', value: 'High-Gloss' },
            { key: 'Application', value: 'Flooring, Feature Walls' },
            { key: 'Thickness', value: '18 mm' },
        ],
    },
    {
        _id: 'dummy-7',
        name: 'Micro Cement Charcoal',
        color: 'Charcoal',
        price: 5500,
        mrp: 6500,
        selling_price: 5500,
        images: ['/Images/Image_7.png'],
        category: 'Concrete',
        product_type: 'Concrete',
        skucode: 'MC-CHR-007',
        dynamicAttributes: [
            { key: 'Finish', value: 'Satin' },
            { key: 'Application', value: 'Floors, Walls, Counters' },
            { key: 'Waterproof', value: 'Yes' },
        ],
    },
    {
        _id: 'dummy-8',
        name: 'Velvet Felt Sage Green',
        color: 'Green',
        price: 2200,
        mrp: 2800,
        selling_price: 2200,
        images: ['/Images/Image_8.png'],
        category: 'Felt',
        product_type: 'Felt',
        skucode: 'VF-SGN-008',
        dynamicAttributes: [
            { key: 'Material', value: 'Wool-Blend Felt' },
            { key: 'Thickness', value: '3 mm' },
            { key: 'Width', value: '180 cm' },
        ],
    },
    {
        _id: 'dummy-9',
        name: 'Brushed Brass Metallic',
        color: 'Gold',
        price: 8900,
        mrp: 10500,
        selling_price: 8900,
        images: ['/Images/Image_9.png'],
        category: 'Metal',
        product_type: 'Metal',
        skucode: 'BB-GLD-009',
        dynamicAttributes: [
            { key: 'Finish', value: 'Brushed' },
            { key: 'Sheet Thickness', value: '1.2 mm' },
            { key: 'Application', value: 'Accents, Furniture, Cladding' },
        ],
    },
    {
        _id: 'dummy-10',
        name: 'Leather Cognac Full-Grain',
        color: 'Cognac',
        price: 15000,
        mrp: 18000,
        selling_price: 15000,
        images: ['/Images/Image_10.png'],
        category: 'Leather',
        product_type: 'Leather',
        skucode: 'LC-COG-010',
        dynamicAttributes: [
            { key: 'Grade', value: 'Full-Grain' },
            { key: 'Thickness', value: '1.5 mm' },
            { key: 'Width', value: '120–140 cm' },
        ],
    },
    {
        _id: 'dummy-11',
        name: 'Laminate Walnut Grain',
        color: 'Walnut',
        price: 1200,
        mrp: 1600,
        selling_price: 1200,
        images: ['/Images/Image_11.png'],
        category: 'Laminate',
        product_type: 'Laminate',
        skucode: 'LW-WAL-011',
        dynamicAttributes: [
            { key: 'Finish', value: 'Textured' },
            { key: 'Thickness', value: '1 mm' },
            { key: 'Application', value: 'Furniture, Cabinets' },
        ],
    },
    {
        _id: 'dummy-12',
        name: 'Porcelain Cool Stone',
        color: 'Grey',
        price: 3800,
        mrp: 4500,
        selling_price: 3800,
        images: ['/Images/Rectangle_4.jpg'],
        category: 'Stone',
        product_type: 'Stone',
        skucode: 'PC-CST-012',
        dynamicAttributes: [
            { key: 'Finish', value: 'Lappato' },
            { key: 'Size', value: '800 × 1600 mm' },
            { key: 'Thickness', value: '9 mm' },
        ],
    },
];
